Adds endpoint to get training job info. E2E test for train, generate. Unit tests.

diff --git a/scripts/cray b/scripts/cray
--- a/scripts/cray
+++ b/scripts/cray
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -151,6 +151,13 @@ cray_test_usage() {
     printf "  %s\n" "--coverage-path COVERAGE-PATH"
     printf "    Absolute path to a directory to write coverage results into\n"
     printf "    %s\n" "Default: /tmp/cray/coverage"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--log-cli-level LOG-CLI-LEVEL"
+    printf "    Set log level\n"
+    printf "    %s\n" "Allowed: INFO, DEBUG, ERROR"
+    printf "    %s\n" "Default: DEBUG"
     echo
 
     # :flag.usage
@@ -390,15 +397,6 @@ inspect_args() {
     echo args: none
   fi
 
-  if ((${#other_args[@]})); then
-    echo
-    echo other_args:
-    echo "- \${other_args[*]} = ${other_args[*]}"
-    for i in "${!other_args[@]}"; do
-      echo "- \${other_args[$i]} = ${other_args[$i]}"
-    done
-  fi
-
   if ((${#deps[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
@@ -511,7 +509,7 @@ cray_depot_build_command() {
       docker_platform=("linux/amd64")
   fi
 
-  docker_build_command="depot build --platform ${docker_platform} --build-arg BASE_NAME=${target} --build-arg VLLM_TARGET_DEVICE=${vllm_target_device} -t gdiamos/masint-$target:latest --push ."
+  docker_build_command="depot build --platform ${docker_platform} --build-arg BASE_NAME=${target} --build-arg VLLM_TARGET_DEVICE=${vllm_target_device} -t sudnya/smi-platform:nvidia-latest --push ."
 
   # Run docker build command
   echo $(green_bold Building image with command: ${docker_build_command})
@@ -527,7 +525,7 @@ cray_up_command() {
   # cmd/up_command.sh
   #inspect_args
 
-  docker compose -f docker-compose.yaml up --build
+  docker compose -f docker-compose.yaml up --build --force-recreate
 
 }
 
@@ -1085,6 +1083,20 @@ cray_test_parse_requirements() {
         ;;
 
       # :flag.case
+      --log-cli-level)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--log-cli-level']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--log-cli-level requires an argument: --log-cli-level LOG-CLI-LEVEL" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
       --verbose)
 
         # :flag.case_arg
@@ -1137,10 +1149,15 @@ cray_test_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['test-path']:-} ]] || args['test-path']="test/infra/*"
   [[ -n ${args['--coverage-path']:-} ]] || args['--coverage-path']="/tmp/cray/coverage"
+  [[ -n ${args['--log-cli-level']:-} ]] || args['--log-cli-level']="DEBUG"
   [[ -n ${args['--verbose']:-} ]] || args['--verbose']="no"
   [[ -n ${args['--workers']:-} ]] || args['--workers']="auto"
 
   # :command.whitelist_filter
+  if [[ ${args['--log-cli-level']:-} ]] && [[ ! ${args['--log-cli-level']:-} =~ ^(INFO|DEBUG|ERROR)$ ]]; then
+    printf "%s\n" "--log-cli-level must be one of: INFO, DEBUG, ERROR" >&2
+    exit 1
+  fi
   if [[ ${args['--verbose']:-} ]] && [[ ! ${args['--verbose']:-} =~ ^(yes|no)$ ]]; then
     printf "%s\n" "--verbose must be one of: yes, no" >&2
     exit 1
@@ -1483,15 +1500,16 @@ initialize() {
   long_usage=''
   set -e
 
+  # :command.globals
+  declare -g -A args=()
+  declare -g -A deps=()
+  declare -g -a env_var_names=()
+  declare -g -a input=()
+
 }
 
 # :command.run
 run() {
-  declare -g -A args=()
-  declare -g -A deps=()
-  declare -g -a other_args=()
-  declare -g -a env_var_names=()
-  declare -g -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
